In [1]:
import numpy as np
a=np.array([1,1,0])
b=np.array([-1,2,5])
M=np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
np.inner(a,b) #inner product

1

In [2]:
M.dot(b) #matrix vector multiplication

array([-4,  0,  8])

In [3]:
np.linalg.norm(b) #find norm


5.477225575051661

In [6]:
import scipy.linalg as linalg  #LU decomposition
LU=linalg.lu_factor(M)
x=linalg.lu_solve(LU,b)
print(x)

[1.5 4.  4.5]


In [7]:
CH=linalg.cho_factor(M) #Cholesky decomposition
x=linalg.cho_solve(CH,b)
print(x)


[1.5 4.  4.5]
